name: Convert GLTF to DirectX (.X) file

on:
  push:
    paths:
      - "*.gltf"  # Run the action when a GLTF file is pushed

jobs:
  convert:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        
      - name: Install Assimp
        run: |
          sudo apt-get update
          sudo apt-get install -y assimp-utils

      - name: Convert GLTF to .X
        run: |
          mkdir -p converted
          for file in *.gltf; do
            assimp export "$file" "converted/${file%.gltf}.x"
          done

      - name: Upload converted .X files
        uses: actions/upload-artifact@v4
        with:
          name: converted-x-files
          path: ./converted/*.x
